# Generated by Django 5.1.1 on 2024-10-07 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_for", models.CharField(max_length=255)),
                ("video_type", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("turning", models.IntegerField(blank=True, null=True)),
                ("public_permissions", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        limit_choices_to={"is_influencer": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencer_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
