# Generated by Django 5.1.1 on 2024-10-07 21:15

import enumfields.fields
import video_requests.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videorequest",
            name="video_type",
            field=enumfields.fields.EnumField(
                default=5, enum=video_requests.enums.VideoType, max_length=69
            ),
        ),
    ]
