# Generated by Django 5.1.1 on 2024-10-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_requests", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="videorequest",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
